### PR TITLE
Various Enhancements

### PR DESCRIPTION
**Pull request by sanssecours**
Hi Arne,

this pull request contains various minor enhancements for the bundle. I hope you like them. If I should change anything, then please just comment below.

For the new installation instructions (commit 36deef3) to work, you have to change the name of the bundle to `EBNF.tmbundle`. You can do that in “Settings→Repository name”.

Kind regards,
  René

### CODE REVIEW

**Comment by arne-schroppe** [comment]
Hi René,

this looks great! Thanks for putting in the effort to improve this little weekend-project. I'll merge it.

But as you can probably tell, I am not actively maintaining this repository anymore. Would you be interested in taking it over? It is mainly your work now anyway.
If you are interested, I would transfer ownership of the repository to your account. Just comment here if that is fine with you.

Best,
Arne

**Comment by sanssecours** [comment]
Thanks for merging :o).

> Would you be interested in taking it over?

Certainly.

> If you are interested, I would transfer ownership of the repository to your account. Just comment here if that is fine with you.

Yeah, that sounds great. Thank you!

**Comment by arne-schroppe** [comment]
Ok, I tried transferring ownership, but got this error message:
```
sanssecours already has a repository in the arne-schroppe/ebnf-textmate-bundle network
```
So I assume you need to delete your fork first. I'll try again when you've done that.

**Comment by sanssecours** [comment]
> So I assume you need to delete your fork first. I'll try again when you've done that.

Thank you for the information. I just deleted my copy of the bundle.

**Comment by arne-schroppe** [comment]
Perfect, now it worked. I think you'll get an email now. Have fun with the repo and thanks again for adopting it :)

**Pull request merged**
